ci: ignore fuzzing checks on python features (#131)
* ci: only fuzz when core crate modified

* chore: remove windows from runners matrix

* skip everything else if src didn't change

* require ci-pass and not tests

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -13,11 +13,29 @@ env:
   RUSTDOCFLAGS: "-D warnings"
 
 jobs:
+  filter-changes:
+    runs-on: ubuntu-latest
+    outputs:
+      src-changed: ${{ steps.filter.outputs.src }}
+    steps:
+      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
+      - name: Detect Changes
+        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
+        id: filter
+        with:
+          predicate-quantifier: 'every'
+          filters: |
+            src:
+              - 'src/**'
+              - '!src/python.rs'
+
   test:
     runs-on: ${{ matrix.os }}
+    needs: filter-changes
+    if: ${{ needs.filter-changes.outputs.src-changed == 'true' }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        os: [ubuntu-latest, macos-latest]
         rust:
           - stable
           - beta
@@ -37,6 +55,8 @@ jobs:
 
   lint:
     runs-on: ubuntu-latest
+    needs: filter-changes
+    if: ${{ needs.filter-changes.outputs.src-changed == 'true' }}
     steps:
       - uses: actions/checkout@v1
       - uses: dtolnay/rust-toolchain@1.89
@@ -59,6 +79,8 @@ jobs:
 
   fuzzer:
     runs-on: ubuntu-latest
+    needs: filter-changes
+    if: ${{ needs.filter-changes.outputs.src-changed == 'true' }}
     steps:
       - uses: actions/checkout@v1
       - uses: dtolnay/rust-toolchain@1.89
@@ -66,3 +88,15 @@ jobs:
         env:
           HANNOY_FUZZ_DURATION_SEC: 1800
         run: cargo test -- random_read_writes
+
+  ci-pass:
+    runs-on: ubuntu-latest
+    if: always()
+    needs: [test, lint, fuzzer]
+    steps:
+      - name: Verify CI results
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more jobs failed or were cancelled"
+            exit 1
+          fi
